# vim:ft=ansible:
---

- hosts: graylog
  user: vagrant
  become: yes
  become_method: sudo
  roles:
  - { role: common }
  - { role: nfs, mode: "client" }
  - { role: firewalld }
  - { role: graylog-ansible/roles/common, tags: common } 
  - { role: graylog-ansible/roles/nginx, tags: nginx }
  - { role: graylog-ansible/roles/mongodb, tags: mongodb } 
  - { role: graylog-ansible/roles/elasticsearch, tags: elasticsearch }
  - { role: graylog-ansible/roles/graylog, tags: graylog }
  - { role: graylog-ansible/roles/finish, tags: finish }
  - { role: syslog-ng-client }

- hosts: syslog-ng
  user: vagrant
  become: yes
  become_method: sudo
  roles:
  - { role: common }
  - { role: firewalld }
  - { role: nfs, mode: "server" }
  - { role: syslog-ng-client }
  - { role: syslog-ng-server }
  - { role: ansible-role-nfs  }

- hosts: client
  user: vagrant
  become: yes
  become_method: sudo
  roles:
  - { role: common }
  - { role: firewalld }
  - { role: syslog-ng-client }

- hosts: switch
  user: vagrant
  become: yes
  become_method: sudo
  roles:
  - { role: switch }
