---

- name: Unistall rsyslog
  yum: name="rsyslog" state=absent

- name: Install new syslog-ng and re-install cron
  yum:  update_cache=yes name={{ item }}
       state=installed
  with_items:
    - syslog-ng
    - logrotate
    - cronie
    - cronie-anacron
    - crontabs

- name: Copy log modules configuration
  copy: src=modules.conf dest=/etc/syslog-ng/modules.conf owner=root group=root
  notify:
    - restart syslog-ng

- name: Set syslog-ng configuration
  template: src=syslog-ng.conf.j2 dest=/etc/syslog-ng/syslog-ng.conf owner=root group=root
  notify:
    - restart syslog-ng

- name: Ensure syslog-ng is running
  service: name=syslog-ng state=started enabled=yes

###########################
# Log rotation
###########################
- name: Copy logrotate configuration
  template: src=logrotate.conf.j2 dest=/etc/logrotate.conf

- name: Install syslog logrotate configuration
  copy: src=syslog.logrotate dest=/etc/logrotate.d/syslog owner=root group=root mode=0644

